# Generated by Django 4.2.11 on 2024-05-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'verbose_name': 'Drone', 'verbose_name_plural': 'Drones'},
        ),
    ]
