# Generated by Django 4.2.11 on 2024-05-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0002_alter_drone_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="img",
            field=models.ImageField(upload_to="static/img/drones"),
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("value", models.CharField(max_length=225)),
                (
                    "Drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drones.drone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Specification",
                "verbose_name_plural": "Specifications",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("description", models.TextField()),
                ("icon", models.ImageField(upload_to="")),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drones.drone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
    ]
