# Generated by Django 4.2.11 on 2024-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0003_alter_drone_img_specification_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/img/drones"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/drones/features"
            ),
        ),
    ]
