# Generated by Django 4.2.11 on 2024-05-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_alter_drone_img_alter_feature_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="specification",
            old_name="Drone",
            new_name="drone",
        ),
    ]
