# Generated by Django 4.2.11 on 2024-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0005_rename_drone_specification_drone"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drone",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/drones/img"
            ),
        ),
    ]
