# Generated by Django 4.2.11 on 2024-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0006_drone_description_alter_drone_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="img",
            field=models.ImageField(
                default="static/drones/default.jpg", upload_to="static/drones/img"
            ),
        ),
    ]
