# Generated by Django 4.2.11 on 2024-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0007_alter_drone_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drone",
            name="img",
        ),
        migrations.AddField(
            model_name="drone",
            name="image",
            field=models.ImageField(
                default="drones/img/default.png", upload_to="drones/img"
            ),
        ),
    ]
