# Generated by Django 4.2.11 on 2024-05-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0009_alter_drone_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drone",
            name="image",
        ),
    ]
