# Generated by Django 4.2.11 on 2024-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0010_remove_drone_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="featured_image",
            field=models.ImageField(default="default.png", upload_to="drones/"),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="drones/features"),
        ),
    ]
