# Generated by Django 4.2.11 on 2024-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0011_drone_featured_image_alter_feature_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="specification",
            name="icon",
            field=models.ImageField(
                default="drones/specifications/default.png",
                upload_to="drones/specifications",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.ImageField(
                default="drones/features/default.png", upload_to="drones/features"
            ),
        ),
    ]
