# Generated by Django 4.2.11 on 2024-05-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0013_droneimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DroneImage",
        ),
    ]
