# Generated by Django 4.2.11 on 2024-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0015_droneimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="droneimage",
            name="caption",
            field=models.TextField(
                blank=True, default="This is the default description"
            ),
            preserve_default=False,
        ),
    ]
