# Generated by Django 4.2.11 on 2024-05-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("position", models.CharField(max_length=155)),
                ("image", models.ImageField(upload_to="core/img/members")),
                ("linkedin", models.URLField()),
                ("instagram", models.URLField()),
                ("twitter", models.URLField()),
            ],
        ),
    ]
