# Generated by Django 4.2.11 on 2024-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="brief",
            field=models.TextField(blank=True, null=True),
        ),
    ]
