# Generated by Django 4.2.11 on 2024-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_member_brief"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                default="img/default.png", upload_to="core/img/services"
            ),
        ),
    ]
